# Site settings
title:          Lectures
description:    "Collection of lecture reports."
#url:            https://github.com/inelaah/rain

# Author
author:
  name:         Haowei Guo
#  email:        inelaah@gmail.com
#  url:          https://inelaah.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
   - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: 2499032660@qq.com
  github: https://github.com/hwei-esay
#  twitter: https://twitter.com
#  linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
